# Generated by Django 5.2.13 on 2026-04-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryshipment_exception_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryshipment',
            new_name='delivery_de_status_4feae9_idx',
            old_name='delivery_shi_status_75935f_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryshipment',
            new_name='delivery_de_trackin_b9deba_idx',
            old_name='delivery_shi_trackin_f31d8d_idx',
        ),
    ]
