# Generated by Django 5.2.13 on 2026-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('payment_update', 'Payment Update'), ('prescription_update', 'Prescription Update'), ('inventory_alert', 'Inventory Alert'), ('system_alert', 'System Alert'), ('account', 'Account')], default='account', max_length=32),
        ),
    ]
