# Generated by Django 5.2.13 on 2026-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_fulfillment_status_and_tracking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('placed', 'Placed'), ('payment_session_started', 'Payment Session Started'), ('payment_retry_started', 'Payment Retry Started'), ('payment_captured', 'Payment Captured'), ('payment_failed', 'Payment Failed'), ('refund_requested', 'Refund Requested'), ('refund_completed', 'Refund Completed'), ('fulfillment_updated', 'Fulfillment Updated'), ('cancelled', 'Cancelled'), ('status_updated', 'Status Updated'), ('payment_status_updated', 'Payment Status Updated'), ('note_updated', 'Note Updated')], max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='settlementbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('closed', 'Closed')], default='draft', max_length=16),
        ),
    ]
