# Generated by Django 5.2.13 on 2026-04-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_product_f7e8af_idx',
            old_name='inventory_i_product_5f36d8_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_product_5919a9_idx',
            old_name='inventory_s_product_5fc641_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_locatio_b95d2f_idx',
            old_name='inventory_s_locatio_2d5cc5_idx',
        ),
    ]
