from django.urls import path

from .views import (
    AdminOrderDetailView,
    AdminOrderListView,
    AdminPaymentAttemptListView,
    AdminReconciliationExportView,
    AdminReconciliationSummaryView,
    AdminRefundDecisionView,
    AdminSettlementBatchDetailView,
    AdminSettlementBatchExportView,
    AdminSettlementBatchListCreateView,
    AdminSettlementBatchUpdateView,
    AdminSummaryView,
    OrderCancelView,
    OrderCheckoutView,
    OrderDetailView,
    OrderInvoiceDownloadView,
    OrderListView,
    OrderPaymentRetryView,
    PaymentWebhookView,
    OrderPaymentSessionView,
    OrderPaymentConfirmView,
    OrderPaymentVerifyView,
    OrderRefundRequestView,
)


urlpatterns = [
    path("", OrderListView.as_view(), name="order-list"),
    path("admin-orders/", AdminOrderListView.as_view(), name="order-admin-list"),
    path("admin-orders/<str:order_number>/", AdminOrderDetailView.as_view(), name="order-admin-detail"),
    path("admin-payments/", AdminPaymentAttemptListView.as_view(), name="order-admin-payments"),
    path("admin-reconciliation/", AdminReconciliationSummaryView.as_view(), name="order-admin-reconciliation"),
    path("admin-reconciliation/export/", AdminReconciliationExportView.as_view(), name="order-admin-reconciliation-export"),
    path("admin-settlements/", AdminSettlementBatchListCreateView.as_view(), name="order-admin-settlements"),
    path("admin-settlements/<int:id>/", AdminSettlementBatchDetailView.as_view(), name="order-admin-settlement-detail"),
    path("admin-settlements/<int:id>/update/", AdminSettlementBatchUpdateView.as_view(), name="order-admin-settlement-update"),
    path("admin-settlements/<int:batch_id>/export/", AdminSettlementBatchExportView.as_view(), name="order-admin-settlement-export"),
    path("admin-orders/<str:order_number>/refund/", AdminRefundDecisionView.as_view(), name="order-admin-refund"),
    path("admin-summary/", AdminSummaryView.as_view(), name="order-admin-summary"),
    path("payments/webhook/", PaymentWebhookView.as_view(), name="order-payment-webhook"),
    path("checkout/", OrderCheckoutView.as_view(), name="order-checkout"),
    path("<str:order_number>/", OrderDetailView.as_view(), name="order-detail"),
    path("<str:order_number>/invoice/", OrderInvoiceDownloadView.as_view(), name="order-invoice-download"),
    path("<str:order_number>/cancel/", OrderCancelView.as_view(), name="order-cancel"),
    path("<str:order_number>/payment/session/", OrderPaymentSessionView.as_view(), name="order-payment-session"),
    path("<str:order_number>/payment/retry/", OrderPaymentRetryView.as_view(), name="order-payment-retry"),
    path("<str:order_number>/payment/confirm/", OrderPaymentConfirmView.as_view(), name="order-payment-confirm"),
    path("<str:order_number>/payment/verify/", OrderPaymentVerifyView.as_view(), name="order-payment-verify"),
    path("<str:order_number>/refund/", OrderRefundRequestView.as_view(), name="order-refund-request"),
]
