# Generated by Django 5.2.13 on 2026-04-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_event_t_ac78f0_idx',
            old_name='audit_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_entity__9535bf_idx',
            old_name='audit_entity_idx',
        ),
    ]
