# Generated by Django 5.2.13 on 2026-04-17 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=24, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('uploaded_file_url', models.URLField(blank=True)),
                ('uploaded_file_type', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('clarification_required', 'Clarification Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=32)),
                ('review_priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('review_eta_hours', models.PositiveIntegerField(default=4)),
                ('clarification_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('clarification_required', 'Clarification Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('substitute_guidance', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='prescriptions.prescription')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['reference_code'], name='prescriptio_referen_50e347_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'review_priority', 'created_at'], name='prescriptio_status_bdf6dc_idx'),
        ),
    ]
