# Generated by Django 5.2.13 on 2026-04-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_storage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='storage_backend',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
