# Generated by Django 5.2.13 on 2026-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_viewer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('catalog_manager', 'Catalog Manager'), ('pharmacist', 'Pharmacist'), ('warehouse_operator', 'Warehouse Operator'), ('support_agent', 'Support Agent'), ('finance', 'Finance'), ('viewer', 'Viewer')], default='customer', max_length=32),
        ),
    ]
