# Generated by Django 5.2.13 on 2026-04-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('suspended', 'Suspended')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('super_admin', 'Super Admin'), ('admin', 'Admin'), ('catalog_manager', 'Catalog Manager'), ('pharmacist', 'Pharmacist'), ('warehouse_operator', 'Warehouse Operator'), ('support_agent', 'Support Agent'), ('finance', 'Finance'), ('viewer', 'Viewer')], default='customer', max_length=32),
        ),
    ]
