from django.urls import path

from .views import (
    AdminUserActivityReportView,
    AdminUserAuditView,
    AdminUserAuditReportView,
    AdminUserBulkActionView,
    AdminUserDetailView,
    AdminUserEmployeeCodeGenerateView,
    AdminUserEmployeeCodeLookupView,
    AdminUserExportView,
    AdminUserLocationOptionsView,
    AdminUserListCreateView,
    AdminUserLockToggleView,
    AdminUserResetPasswordView,
    AdminUsernameGenerateView,
    CustomerWebsiteActivityHeartbeatView,
    MyAddressDetailView,
    MyAddressListCreateView,
    MyPaymentMethodDetailView,
    MyPaymentMethodListCreateView,
    RolePermissionMatrixDetailAPI,
    RolePermissionMatrixListUpdateAPI,
    UserSavedFilterViewDetailAPI,
    UserSavedFilterViewListCreateAPI,
    logout,
    me,
    send_otp,
    verify_otp,
)


urlpatterns = [
    path("send-otp/", send_otp, name="auth-send-otp"),
    path("verify-otp/", verify_otp, name="auth-verify-otp"),
    path("me/", me, name="auth-me"),
    path("logout/", logout, name="auth-logout"),
    path("activity/heartbeat/", CustomerWebsiteActivityHeartbeatView.as_view(), name="auth-activity-heartbeat"),
    path("addresses/", MyAddressListCreateView.as_view(), name="auth-address-list-create"),
    path("addresses/<int:pk>/", MyAddressDetailView.as_view(), name="auth-address-detail"),
    path("payment-methods/", MyPaymentMethodListCreateView.as_view(), name="auth-payment-method-list-create"),
    path("payment-methods/<int:pk>/", MyPaymentMethodDetailView.as_view(), name="auth-payment-method-detail"),
    path("admin/users/", AdminUserListCreateView.as_view(), name="admin-user-list-create"),
    path("admin/users/username/generate/", AdminUsernameGenerateView.as_view(), name="admin-username-generate"),
    path("admin/users/employee-code/generate/", AdminUserEmployeeCodeGenerateView.as_view(), name="admin-user-employee-code-generate"),
    path("admin/users/employee-code/lookup/", AdminUserEmployeeCodeLookupView.as_view(), name="admin-user-employee-code-lookup"),
    path("admin/users/location-options/", AdminUserLocationOptionsView.as_view(), name="admin-user-location-options"),
    path("admin/users/export/", AdminUserExportView.as_view(), name="admin-user-export"),
    path("admin/users/reports/activity/", AdminUserActivityReportView.as_view(), name="admin-user-activity-report"),
    path("admin/users/reports/audit/", AdminUserAuditReportView.as_view(), name="admin-user-audit-report"),
    path("admin/users/bulk-actions/", AdminUserBulkActionView.as_view(), name="admin-user-bulk-action"),
    path("admin/users/saved-views/", UserSavedFilterViewListCreateAPI.as_view(), name="admin-user-saved-view-list-create"),
    path("admin/users/saved-views/<int:pk>/", UserSavedFilterViewDetailAPI.as_view(), name="admin-user-saved-view-detail"),
    path("admin/users/permissions/", RolePermissionMatrixListUpdateAPI.as_view(), name="admin-user-permission-list-create"),
    path("admin/users/permissions/<int:pk>/", RolePermissionMatrixDetailAPI.as_view(), name="admin-user-permission-detail"),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("admin/users/<int:pk>/reset-password/", AdminUserResetPasswordView.as_view(), name="admin-user-reset-password"),
    path("admin/users/<int:pk>/audit/", AdminUserAuditView.as_view(), name="admin-user-audit"),
    path("admin/users/<int:pk>/<str:action>/", AdminUserLockToggleView.as_view(), name="admin-user-lock-toggle"),
]
